services:
  - type: web
    name: e-cock
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - e-cock.onrender.com
    databases:
      - name: e-cock-db
        databaseName: e-cock
        user: e-cock
        plan: free 